// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://ejemplo.com/terminos",
        "contact": {
            "name": "Equipo de Backend",
            "email": "backend@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Autentica un usuario con email y contraseña, retornando información del usuario y token de acceso",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Autenticar usuario",
                "parameters": [
                    {
                        "description": "Credenciales de login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login exitoso",
                        "schema": {
                            "$ref": "#/definitions/response.LoginSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "$ref": "#/definitions/response.LoginBadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Credenciales inválidas",
                        "schema": {
                            "$ref": "#/definitions/response.LoginErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Usuario inactivo",
                        "schema": {
                            "$ref": "#/definitions/response.LoginErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.LoginErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/roles-permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene los roles y permisos del usuario autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Obtener roles y permisos del usuario",
                "responses": {
                    "200": {
                        "description": "Roles y permisos obtenidos exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.UserRolesPermissionsSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.LoginErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.LoginErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.LoginErrorResponse"
                        }
                    }
                }
            }
        },
        "/business-types": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene la lista completa de tipos de negocio disponibles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BusinessType"
                ],
                "summary": "Obtener todos los tipos de negocio",
                "responses": {
                    "200": {
                        "description": "Tipos de negocio obtenidos exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeListSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un nuevo tipo de negocio con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BusinessType"
                ],
                "summary": "Crear tipo de negocio",
                "parameters": [
                    {
                        "description": "Datos del tipo de negocio",
                        "name": "businessType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.BusinessTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tipo de negocio creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Código ya existe",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    }
                }
            }
        },
        "/business-types/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene un tipo de negocio específico por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BusinessType"
                ],
                "summary": "Obtener tipo de negocio por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del tipo de negocio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tipo de negocio obtenido exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Tipo de negocio no encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza un tipo de negocio existente con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BusinessType"
                ],
                "summary": "Actualizar tipo de negocio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del tipo de negocio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del tipo de negocio",
                        "name": "businessType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.BusinessTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tipo de negocio actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o ID inválido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Tipo de negocio no encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Código ya existe",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina un tipo de negocio existente por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BusinessType"
                ],
                "summary": "Eliminar tipo de negocio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del tipo de negocio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tipo de negocio eliminado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Tipo de negocio no encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessTypeErrorResponse"
                        }
                    }
                }
            }
        },
        "/businesses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene la lista completa de negocios disponibles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Business"
                ],
                "summary": "Obtener todos los negocios",
                "responses": {
                    "200": {
                        "description": "Negocios obtenidos exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessListSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un nuevo negocio con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Business"
                ],
                "summary": "Crear negocio",
                "parameters": [
                    {
                        "description": "Datos del negocio",
                        "name": "business",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.BusinessRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Negocio creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Código o dominio ya existe",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    }
                }
            }
        },
        "/businesses/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene un negocio específico por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Business"
                ],
                "summary": "Obtener negocio por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del negocio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Negocio obtenido exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Negocio no encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza un negocio existente con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Business"
                ],
                "summary": "Actualizar negocio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del negocio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del negocio",
                        "name": "business",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.BusinessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Negocio actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o ID inválido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Negocio no encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Código o dominio ya existe",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina un negocio existente por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Business"
                ],
                "summary": "Eliminar negocio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del negocio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Negocio eliminado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token de acceso requerido",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Negocio no encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/response.BusinessErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients": {
            "get": {
                "description": "Este endpoint permite obtener la lista de todos los clientes registrados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clientes"
                ],
                "summary": "Obtiene todos los clientes",
                "responses": {
                    "200": {
                        "description": "Lista de clientes obtenida exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Este endpoint permite crear un nuevo cliente para un restaurante.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clientes"
                ],
                "summary": "Crea un nuevo cliente",
                "parameters": [
                    {
                        "description": "Datos del cliente",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Client"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Cliente creado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/clients/{id}": {
            "get": {
                "description": "Este endpoint permite obtener los datos de un cliente específico por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clientes"
                ],
                "summary": "Obtiene un cliente por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cliente obtenido exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Cliente no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Este endpoint permite actualizar parcialmente los datos de un cliente. Solo se modifican los campos enviados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clientes"
                ],
                "summary": "Actualiza un cliente existente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del cliente a actualizar",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateClient"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cliente actualizado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Cliente no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Este endpoint permite eliminar un cliente existente del sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clientes"
                ],
                "summary": "Elimina un cliente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cliente eliminado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Cliente no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reserves": {
            "get": {
                "description": "Este endpoint obtiene todas las reservas con información completa de cliente, mesa, restaurante y estado. Soporta filtros opcionales.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas"
                ],
                "summary": "Obtiene todas las reservas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del estado de reserva",
                        "name": "status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID del cliente",
                        "name": "client_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la mesa",
                        "name": "table_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha de inicio (formato RFC3339: 2024-01-01T00:00:00Z)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha de fin (formato RFC3339: 2024-12-31T23:59:59Z)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de reservas obtenida exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Parámetros inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Este endpoint permite crear una nueva reserva para una mesa en un restaurante.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas"
                ],
                "summary": "Crea una nueva reserva",
                "parameters": [
                    {
                        "description": "Datos de la reserva",
                        "name": "reservation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Reservation"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Reserva creada exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reserves/{id}": {
            "get": {
                "description": "Este endpoint obtiene una reserva específica con información completa de cliente, mesa, restaurante y estado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas"
                ],
                "summary": "Obtiene una reserva por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la reserva",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reserva obtenida exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Reserva no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Este endpoint permite actualizar campos específicos de una reserva existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas"
                ],
                "summary": "Actualiza una reserva",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la reserva",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos para actualizar",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateReservation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reserva actualizada exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Reserva no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reserves/{id}/cancel": {
            "patch": {
                "description": "Este endpoint permite cancelar una reserva existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas"
                ],
                "summary": "Cancela una reserva",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la reserva",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Razón de cancelación (opcional)",
                        "name": "cancel",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.CancelReservation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reserva cancelada exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Reserva no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tables": {
            "get": {
                "description": "Este endpoint permite obtener la lista de todas las mesas registradas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mesas"
                ],
                "summary": "Obtiene todas las mesas",
                "responses": {
                    "200": {
                        "description": "Lista de mesas obtenida exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Este endpoint permite crear una nueva mesa para un restaurante.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mesas"
                ],
                "summary": "Crea una nueva mesa",
                "parameters": [
                    {
                        "description": "Datos de la mesa",
                        "name": "table",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Table"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Mesa creada exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Mesa ya existe para este restaurante",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tables/{id}": {
            "get": {
                "description": "Este endpoint permite obtener los datos de una mesa específica por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mesas"
                ],
                "summary": "Obtiene una mesa por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la mesa",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mesa obtenida exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Mesa no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Este endpoint permite actualizar parcialmente los datos de una mesa. Solo se modifican los campos enviados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mesas"
                ],
                "summary": "Actualiza una mesa existente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la mesa",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de la mesa a actualizar",
                        "name": "table",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateTable"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mesa actualizada exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Mesa no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Mesa con ese número ya existe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Este endpoint permite eliminar una mesa existente del sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mesas"
                ],
                "summary": "Elimina una mesa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la mesa",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mesa eliminada exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Mesa no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_infra_primary_http2_handlers_businesshandler_response.BusinessTypeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_infra_primary_http2_handlers_businesstypehandler_response.BusinessTypeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "request.BusinessRequest": {
            "type": "object",
            "required": [
                "business_type_id",
                "code",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "business_type_id": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "custom_domain": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "enable_delivery": {
                    "description": "Configuración de funcionalidades",
                    "type": "boolean"
                },
                "enable_pickup": {
                    "type": "boolean"
                },
                "enable_reservations": {
                    "type": "boolean"
                },
                "is_active": {
                    "type": "boolean"
                },
                "logo_url": {
                    "description": "Configuración de marca blanca",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "primary_color": {
                    "type": "string"
                },
                "secondary_color": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "request.BusinessTypeRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.CancelReservation": {
            "type": "object",
            "properties": {
                "reason": {
                    "description": "Razón opcional de cancelación",
                    "type": "string"
                }
            }
        },
        "request.Client": {
            "type": "object",
            "required": [
                "business_id",
                "email",
                "name",
                "phone"
            ],
            "properties": {
                "business_id": {
                    "type": "integer"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "request.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "request.Reservation": {
            "type": "object",
            "required": [
                "business_id",
                "email",
                "end_at",
                "name",
                "number_of_guests",
                "phone",
                "start_at"
            ],
            "properties": {
                "business_id": {
                    "type": "integer"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number_of_guests": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "start_at": {
                    "type": "string"
                }
            }
        },
        "request.Table": {
            "type": "object",
            "required": [
                "business_id",
                "capacity",
                "number"
            ],
            "properties": {
                "business_id": {
                    "type": "integer"
                },
                "capacity": {
                    "type": "integer"
                },
                "number": {
                    "type": "integer"
                }
            }
        },
        "request.UpdateClient": {
            "type": "object",
            "properties": {
                "business_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "request.UpdateReservation": {
            "type": "object",
            "properties": {
                "end_at": {
                    "type": "string"
                },
                "number_of_guests": {
                    "type": "integer"
                },
                "start_at": {
                    "type": "string"
                },
                "table_id": {
                    "type": "integer"
                }
            }
        },
        "request.UpdateTable": {
            "type": "object",
            "properties": {
                "business_id": {
                    "type": "integer"
                },
                "capacity": {
                    "type": "integer"
                },
                "number": {
                    "type": "integer"
                }
            }
        },
        "response.BusinessErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BusinessListResponse": {
            "type": "object",
            "properties": {
                "businesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.BusinessResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.BusinessListSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.BusinessListResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BusinessResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "business_type": {
                    "$ref": "#/definitions/internal_infra_primary_http2_handlers_businesshandler_response.BusinessTypeResponse"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "custom_domain": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "enable_delivery": {
                    "description": "Configuración de funcionalidades",
                    "type": "boolean"
                },
                "enable_pickup": {
                    "type": "boolean"
                },
                "enable_reservations": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "logo_url": {
                    "description": "Configuración de marca blanca",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "primary_color": {
                    "type": "string"
                },
                "secondary_color": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.BusinessSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.BusinessResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BusinessTypeErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BusinessTypeListResponse": {
            "type": "object",
            "properties": {
                "business_types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infra_primary_http2_handlers_businesstypehandler_response.BusinessTypeResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.BusinessTypeListSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.BusinessTypeListResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BusinessTypeSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_infra_primary_http2_handlers_businesstypehandler_response.BusinessTypeResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.LoginBadRequestResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "response.LoginErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "response.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/response.UserInfo"
                }
            }
        },
        "response.LoginSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.LoginResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.PermissionInfo": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                }
            }
        },
        "response.ResourcePermissions": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PermissionInfo"
                    }
                },
                "resource": {
                    "type": "string"
                },
                "resource_name": {
                    "type": "string"
                }
            }
        },
        "response.RoleInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                }
            }
        },
        "response.UserInfo": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_login_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "response.UserRolesPermissionsResponse": {
            "type": "object",
            "properties": {
                "is_super": {
                    "type": "boolean"
                },
                "permissions": {
                    "description": "Mantener para compatibilidad",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PermissionInfo"
                    }
                },
                "resources": {
                    "description": "Nuevo: permisos agrupados por recurso",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ResourcePermissions"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RoleInfo"
                    }
                }
            }
        },
        "response.UserRolesPermissionsSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.UserRolesPermissionsResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Ingrese su token JWT con el prefijo **Bearer**",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Restaurant Reservation API",
	Description:      "Servicio REST para la gestión de reservas multi-restaurante.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
